[2025-07-28T11:22:16.852+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-07-28T11:22:16.883+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: financial_etl_dag.load_data manual__2025-07-28T11:22:10.504935+00:00 [queued]>
[2025-07-28T11:22:16.896+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: financial_etl_dag.load_data manual__2025-07-28T11:22:10.504935+00:00 [queued]>
[2025-07-28T11:22:16.898+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 2
[2025-07-28T11:22:16.916+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): load_data> on 2025-07-28 11:22:10.504935+00:00
[2025-07-28T11:22:16.929+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'financial_etl_dag', 'load_data', 'manual__2025-07-28T11:22:10.504935+00:00', '--job-id', '94', '--raw', '--subdir', 'DAGS_FOLDER/financial_etl_dag.py', '--cfg-path', '/tmp/tmpvhr7e49o']
[2025-07-28T11:22:16.933+0000] {standard_task_runner.py:91} INFO - Job 94: Subtask load_data
[2025-07-28T11:22:16.935+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=1022) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-07-28T11:22:16.937+0000] {standard_task_runner.py:63} INFO - Started process 1024 to run task
[2025-07-28T11:22:17.035+0000] {task_command.py:426} INFO - Running <TaskInstance: financial_etl_dag.load_data manual__2025-07-28T11:22:10.504935+00:00 [running]> on host d6f7a7d3be45
[2025-07-28T11:22:17.152+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='financial_etl_dag' AIRFLOW_CTX_TASK_ID='load_data' AIRFLOW_CTX_EXECUTION_DATE='2025-07-28T11:22:10.504935+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-28T11:22:10.504935+00:00'
[2025-07-28T11:22:17.153+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-07-28T11:22:17.179+0000] {logging_mixin.py:188} INFO - [LOAD] CSV path: /opt/***/dags/data/curated_transactions.csv
[2025-07-28T11:22:17.206+0000] {base.py:84} INFO - Using connection ID '***_db' for task execution.
[2025-07-28T11:22:17.214+0000] {base.py:84} INFO - Using connection ID '***_db' for task execution.
[2025-07-28T11:22:17.220+0000] {sql.py:457} INFO - Running statement: 
    CREATE TABLE IF NOT EXISTS transactions (
        transaction_id INT,
        user_id INT,
        amount FLOAT,
        currency VARCHAR(10),
        timestamp TIMESTAMP,
        merchant VARCHAR(50),
        fraud_flag BOOLEAN
    );
    , parameters: None
[2025-07-28T11:22:17.224+0000] {logging_mixin.py:188} INFO - [LOAD] Ensured transactions table exists.
[2025-07-28T11:22:17.253+0000] {logging_mixin.py:188} INFO - [LOAD] Inserted 3 rows into 'transactions'
[2025-07-28T11:22:17.254+0000] {python.py:237} INFO - Done. Returned value was: None
[2025-07-28T11:22:17.255+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-07-28T11:22:17.265+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=financial_etl_dag, task_id=load_data, execution_date=20250728T112210, start_date=20250728T112216, end_date=20250728T112217
[2025-07-28T11:22:17.318+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-07-28T11:22:17.334+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-07-28T11:22:17.337+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
