[2025-07-30T11:45:35.159+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-07-30T11:45:35.191+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: financial_etl_pipeline.aggregate_monthly_summary manual__2025-07-30T11:45:21.411604+00:00 [queued]>
[2025-07-30T11:45:35.201+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: financial_etl_pipeline.aggregate_monthly_summary manual__2025-07-30T11:45:21.411604+00:00 [queued]>
[2025-07-30T11:45:35.203+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2025-07-30T11:45:35.399+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): aggregate_monthly_summary> on 2025-07-30 11:45:21.411604+00:00
[2025-07-30T11:45:35.418+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=2052) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-07-30T11:45:35.421+0000] {standard_task_runner.py:63} INFO - Started process 2054 to run task
[2025-07-30T11:45:35.420+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'financial_etl_pipeline', 'aggregate_monthly_summary', 'manual__2025-07-30T11:45:21.411604+00:00', '--job-id', '248', '--raw', '--subdir', 'DAGS_FOLDER/financial_etl_dag.py', '--cfg-path', '/tmp/tmptbhuzgzq']
[2025-07-30T11:45:35.427+0000] {standard_task_runner.py:91} INFO - Job 248: Subtask aggregate_monthly_summary
[2025-07-30T11:45:35.515+0000] {task_command.py:426} INFO - Running <TaskInstance: financial_etl_pipeline.aggregate_monthly_summary manual__2025-07-30T11:45:21.411604+00:00 [running]> on host 9c353dd7cf4b
[2025-07-30T11:45:35.608+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='financial_etl_pipeline' AIRFLOW_CTX_TASK_ID='aggregate_monthly_summary' AIRFLOW_CTX_EXECUTION_DATE='2025-07-30T11:45:21.411604+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-30T11:45:21.411604+00:00'
[2025-07-30T11:45:35.610+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-07-30T11:45:35.636+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-07-30T11:45:35.637+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/financial_etl_dag.py", line 102, in aggregate_monthly_summary
    cursor.execute("""
psycopg2.errors.DatatypeMismatch: column "month" is of type timestamp without time zone but expression is of type text
LINE 3:         SELECT TO_CHAR(timestamp, 'YYYY-MM') AS month,
                       ^
HINT:  You will need to rewrite or cast the expression.

[2025-07-30T11:45:35.669+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=financial_etl_pipeline, task_id=aggregate_monthly_summary, execution_date=20250730T114521, start_date=20250730T114535, end_date=20250730T114535
[2025-07-30T11:45:35.693+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 248 for task aggregate_monthly_summary (column "month" is of type timestamp without time zone but expression is of type text
LINE 3:         SELECT TO_CHAR(timestamp, 'YYYY-MM') AS month,
                       ^
HINT:  You will need to rewrite or cast the expression.
; 2054)
[2025-07-30T11:45:35.718+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-07-30T11:45:35.737+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-07-30T11:45:35.740+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
